provider:
  name: tsuga

data_sources:
  team:
    read:
      path: /v1/teams/{id}
      method: GET
  user:
    read:
      path: /v1/users/{id}
      method: GET

resources:
  team:
    create:
      path: /v1/teams
      method: POST
    read:
      path: /v1/teams/{id}
      method: GET
    update:
      path: /v1/teams/{id}
      method: PUT
    delete:
      path: /v1/teams/{id}
      method: DELETE
  retention_policy:
    create:
      path: /v1/retention-policies
      method: POST
    read:
      path: /v1/retention-policies/{id}
      method: GET
    update:
      path: /v1/retention-policies/{id}
      method: PUT
    delete:
      path: /v1/retention-policies/{id}
      method: DELETE
